// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTH_CACHE_KV: KVNamespace;
	ENVIRONMENT: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	DB: D1Database;
}
